ALTER TABLE `mentor` MODIFY COLUMN `firstName` text NOT NULL;--> statement-breakpoint
ALTER TABLE `mentor` MODIFY COLUMN `lastName` text NOT NULL;--> statement-breakpoint
ALTER TABLE `mentor` MODIFY COLUMN `email` text NOT NULL;--> statement-breakpoint
ALTER TABLE `mentor` MODIFY COLUMN `role` int NOT NULL;--> statement-breakpoint
ALTER TABLE `mentor` MODIFY COLUMN `roleOverride` int NOT NULL;--> statement-breakpoint
ALTER TABLE `mentor` MODIFY COLUMN `isVisitor` boolean NOT NULL;--> statement-breakpoint
ALTER TABLE `mentor` MODIFY COLUMN `rating` int NOT NULL;--> statement-breakpoint
ALTER TABLE `sessionType` MODIFY COLUMN `name` text NOT NULL;--> statement-breakpoint
ALTER TABLE `sessionType` MODIFY COLUMN `category` text NOT NULL;--> statement-breakpoint
ALTER TABLE `sessionType` MODIFY COLUMN `length` int NOT NULL;--> statement-breakpoint
ALTER TABLE `session` MODIFY COLUMN `mentor` int NOT NULL;--> statement-breakpoint
ALTER TABLE `session` MODIFY COLUMN `student` int NOT NULL;--> statement-breakpoint
ALTER TABLE `session` MODIFY COLUMN `type` varchar(21) NOT NULL;--> statement-breakpoint
ALTER TABLE `session` MODIFY COLUMN `start` text NOT NULL;--> statement-breakpoint
ALTER TABLE `student` MODIFY COLUMN `firstName` text NOT NULL;--> statement-breakpoint
ALTER TABLE `student` MODIFY COLUMN `lastName` text NOT NULL;--> statement-breakpoint
ALTER TABLE `student` MODIFY COLUMN `email` text NOT NULL;--> statement-breakpoint
ALTER TABLE `student` MODIFY COLUMN `role` int NOT NULL;--> statement-breakpoint
ALTER TABLE `student` MODIFY COLUMN `roleOverride` int NOT NULL;--> statement-breakpoint
ALTER TABLE `student` MODIFY COLUMN `isVisitor` boolean NOT NULL;--> statement-breakpoint
ALTER TABLE `student` MODIFY COLUMN `rating` int NOT NULL;--> statement-breakpoint
ALTER TABLE `userToken` MODIFY COLUMN `user` int NOT NULL;--> statement-breakpoint
ALTER TABLE `user` MODIFY COLUMN `firstName` text NOT NULL;--> statement-breakpoint
ALTER TABLE `user` MODIFY COLUMN `lastName` text NOT NULL;--> statement-breakpoint
ALTER TABLE `user` MODIFY COLUMN `email` text NOT NULL;--> statement-breakpoint
ALTER TABLE `user` MODIFY COLUMN `role` int NOT NULL;--> statement-breakpoint
ALTER TABLE `user` MODIFY COLUMN `roleOverride` int NOT NULL;--> statement-breakpoint
ALTER TABLE `user` MODIFY COLUMN `isVisitor` boolean NOT NULL;--> statement-breakpoint
ALTER TABLE `user` MODIFY COLUMN `rating` int NOT NULL;--> statement-breakpoint
ALTER TABLE `session` ADD `reminded` boolean DEFAULT false NOT NULL;